services:
  - type: web
    name: daraz-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main2:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
